AppBundle\Entity\Workspace:
    type: entity
    table: workspace
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
        dueDate:
            type: datetime
            nullable: false
            column: due_date
        attachment:
            type: boolean
            nullable: true
        workspaceId:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: workspace_id
    lifecycleCallbacks: {  }
